server:
  port: ${PORT:8082}

spring:
  application:
    name: nutrition-service

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never