server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service-auth
          uri: http://nutrex-user:8081
          predicates:
            - Path=/api/auth/**
        - id: user-service-contact
          uri: http://nutrex-user:8081
          predicates:
            - Path=/api/contact/**
        - id: nutrition-service-api
          uri: http://nutrex-nutrition:8082
          predicates:
            - Path=/api/nutrition/**
        - id: plan-service-api
          uri: http://nutrex-plan:8083
          predicates:
            - Path=/api/plans,/api/plans/**
        - id: ai-service-routes
          uri: http://nutrex-ai:8000
          predicates:
            - Path=/nutrition/**,/scan/**,/ai/**