server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 60000
        response-timeout: 120s
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service-auth
          uri: https://nutrex-user-service.onrender.com
          predicates:
            - Path=/api/auth/**
        - id: user-service-contact
          uri: https://nutrex-user-service.onrender.com
          predicates:
            - Path=/api/contact/**
        - id: nutrition-service-api
          uri: https://nutrex-nutrition-service.onrender.com
          predicates:
            - Path=/api/nutrition/**
        - id: plan-service-api
          uri: https://nutrex-plan-service.onrender.com
          predicates:
            - Path=/api/plans,/api/plans/**
        - id: ai-service-routes
          uri: https://nutrex-ai-service.onrender.com
          predicates:
            - Path=/nutrition/**,/scan/**,/ai/**,/api/chat/**,/chat/**,/food/**

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
